import time
import pygame
import Screen

SIZE = 20
BLACK_COLOR = (10, 10, 10)
GRID_COLOR = (40, 40, 40)
GREEN_COLOR = (61, 145, 64)
NUM_COL = 50
NUM_ROW = 25
SHOW_MATRIX = 1
SCREEN_WIDTH = NUM_COL * SIZE
SCREEN_HEIGHT = NUM_ROW * SIZE

SOLDIER_IMAGE = 'soldier.png'
SOLDIER_START = [0, 0]
SOLDIER_SIZE = (40, 80)
SOLDIER_STEP = 1

FLAG_IMAGE = 'flag.png'
FLAG_START = ((NUM_COL - 4) * SIZE, (NUM_ROW - 4) * SIZE)
FLAG_SIZE = (80, 80)

MINE_IMAGE = 'mine.png'
MINE_SIZE = (60, 20)

GRASS_IMAGE = 'grass.png'
GRASS_SIZE = (20, 60)

FPS = 30
FPS_CLOCK = pygame.time.Clock()